services:
  db:
    ports:
      - "5432:5432"

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    volumes:
      - ./apps/api:/app

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      target: runner
      args:
        - BACKEND_API_URL=http://api:8000
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next