services:
  db:
    ports:
      - "5432:5432"
  api:
    image: pfi-api:dev
    ports:
      - "8000:8000"
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    volumes:
      - ./apps/api:/api
      - /api/.venv
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  web:
    image: pfi-web:dev
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./apps/web:/web
      - /web/node_modules
    command: ["pnpm", "dev"]

volumes:
  web_node_modules:
  web_next:
  pnpm_store: